title: Crumbly But Good
author: '@crumblybutgood'
url: https://crumblybutgood.com
description: Richness, Complexity, Nuance, Joy © 2018
header_pages:
 - about.md


show_excerpts: true

rss: rss

permalink: /:year/:month/:day/:title/

plugins:
 - jekyll-feed
 - jekyll-sitemap
 - jekyll-seo-tag
 - jekyll-redirect-from

exclude:
 - README.md
 - Gemfile.lock
 - Gemfile
 - Rakefile
 - CNAME

theme: minima
