name: Crumbly But Good
url: https://crumblybutgood.com
description: Richness, Complexity, Nuance, Joy © 2018
header_pages:
 - about.md

show_excerpts: true

permalink: /:year/:month/:day/:title/
paginate: 10

plugins:
 - jekyll-feed
 - jekyll-paginate
 - jekyll-sitemap
 - jekyll-seo-tag
 - jekyll-redirect-from

exclude:
 - README.md
 - Gemfile.lock
 - Gemfile
 - Rakefile
 - CNAME

theme: minima
